### ISSUE TITLE
[Suggestion] Blank Readme.md file

### ISSUE THREAD

**Issue by smcki012** [handshake-org/HIPs#1]
As we work to provide a templated HIP-001 and Readme, we will first need to initialize the repo. If we start with a blank Readme.md by one of the existing maintainers, I can fork and then submit a PR.

**Comment by tynes** [comment]
What is preventing you from submitting a PR that adds that file?

**Comment by tynes** [comment]
You are right, Github won't let you open a PR if the repo is empty

**Comment by pinheadmz** [comment]
Fixed in https://github.com/handshake-org/HIPs/commit/ac3d8505d8c515b89e78f457c2097cf488c6cb04
thanks!
